[package]
name = "markdown-x"
version = "2.4.0"
description = "A lightweight Markdown editor optimized for computational mechanics"
authors = ["you"]
edition = "2021"

[lib]
name = "markdown_x_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset", "devtools"] }
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
notify = "6.1"
winreg = "0.5.0"
tauri-plugin-opener = "2"
